# Generated by Django 3.0.5 on 2020-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='textfield',
            field=models.TextField(verbose_name=''),
        ),
    ]
